#41: Add syntax highlighting for block comments (#43)
* #41: Removing .idea folder from git tracking since it changes constantly. Adding permanent run configs for important development tasks. Cleaned up build.gradle.kts. Moved plugin description to its own file for easier handling. Swapped out changelog handling code with intellij-changelog plugin. Added linter. Converted java files to .kt and renamed /java to /kotlin. Updated README.md, grammar-kit plugin, and upgraded project to use Java 11

* #41: Added support for parsing block comments

* #41: Adjusting block comment lexing to handle stray */ at beginning-of-line. Added tests. Updated changelog

diff --git a/.github/workflows/build_plugin.yml b/.github/workflows/build_plugin.yml
--- a/.github/workflows/build_plugin.yml
+++ b/.github/workflows/build_plugin.yml
@@ -8,14 +8,11 @@ jobs:
     name: Gradle Wrapper
     runs-on: ubuntu-latest
     steps:
-
-    # Check out current repository
-    - name: Fetch Sources
-      uses: actions/checkout@v2
+    - uses: actions/checkout@v2
 
     # Validate wrapper
     - name: Gradle Wrapper Validation
-      uses: gradle/wrapper-validation-action@v1
+      uses: gradle/wrapper-validation-action@v1.0.3
 
   # Run verifyPlugin and test Gradle tasks
   test:
@@ -23,28 +20,43 @@ jobs:
     needs: gradleValidation
     runs-on: ubuntu-latest
     steps:
+    - uses: actions/checkout@v2
 
-    # Check out current repository
-    - name: Fetch Sources
-      uses: actions/checkout@v2
+    # Verify no java files committed. Note this is run before any gen/* files are created
+    - name: Verify Kotlin Source Files Only
+      run: |
+        javafiles=(`find src -iname *.java`)
+        if [ ${#javafiles[@]} -gt 0 ]
+        then
+          echo "ERROR: Detected a java file in the committed source code! Only kotlin files are allowed." >&2
+          printf '%s\n' "${javafiles[@]}" 1>&2
+          exit 1
+        fi
+        echo "SUCCESS: No java files detected in the committed source code"
 
-    # Setup Java 1.8 environment for the next steps
-    - name: Setup Java
+    # Setup Java 11 environment for the next steps
+    - name: Setup Java 11
       uses: actions/setup-java@v1
       with:
-        java-version: 1.8
+        java-version: 11
 
     # Cache Gradle dependencies
     - name: Setup Cache
-      uses: actions/cache@v1
+      uses: actions/cache@v2
       with:
         path: ~/.gradle/caches
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-        restore-keys: ${{ runner.os }}-gradle-
+        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}
 
-    # Run detekt
-    - name: Run Linters
-      run: ./gradlew check || exit 0
+    # Cache Gradle Wrapper
+    - name: Setup Gradle Wrapper Cache
+      uses: actions/cache@v2
+      with:
+        path: ~/.gradle/wrapper
+        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
+
+    # Run ktlint
+    - name: Run Linter
+      run: ./gradlew ktlintCheck
 
     # Run verifyPlugin Gradle task
     - name: Verify Plugin
@@ -55,7 +67,7 @@ jobs:
       run: ./gradlew test
 
     # Verify code coverage
-    - name: Run Tests
+    - name: Check Code Coverage
       run: ./gradlew checkTestCoverage
 
   # Build plugin with buildPlugin Gradle task and provide the artifact for the next workflow jobs
@@ -65,23 +77,24 @@ jobs:
     needs: test
     runs-on: ubuntu-latest
     steps:
-    # Check out current repository
-    - name: Fetch Sources
-      uses: actions/checkout@v2
-
-    # Setup Java 1.8 environment for the next steps
-    - name: Setup Java
-      uses: actions/setup-java@v1
+    - uses: actions/checkout@v2
+    - uses: actions/setup-java@v1
       with:
-        java-version: 1.8
+        java-version: 11
 
-    # Cache Gradle dependencies
-    - name: Setup Cache
-      uses: actions/cache@v1
+    # Cache Gradle Dependencies
+    - name: Setup Gradle Dependencies Cache
+      uses: actions/cache@v2
       with:
         path: ~/.gradle/caches
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-        restore-keys: ${{ runner.os }}-gradle-
+        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}
+
+    # Cache Gradle Wrapper
+    - name: Setup Gradle Wrapper Cache
+      uses: actions/cache@v2
+      with:
+        path: ~/.gradle/wrapper
+        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
 
     # Build artifact using buildPlugin Gradle task
     - name: Build Plugin
